import { ItemType } from "@/components/ProjectCard";

export const Data: ItemType[] = [
  {
    title: "Trendy",
    info: "Trendy is a comprehensive e-commerce platform designed to provide a seamless shopping experience. The application offers robust authentication, product management, dynamic categorization, and secure checkout features.",
    date: "June - 2024",
    images: ["/ecom-pc.png", "/ecom-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "NextAuth",
      "Shadcn",
      "Stripe",
      "Zustand",
      "Firebase",
      "MongoDB",
      "Resend",
    ],
    website: "https://trendy-sigma.vercel.app/",
    github: "https://github.com/YousifMHelal/trendy",
  },
  {
    title: "Postpeak | Blogging Platform",
    info: "Postpeak is a dynamic blogging platform built with Next.js and Prisma. Users can sign up, log in, create posts, view other posts, comment on them, and filter posts by category. This application provides a user-friendly interface for managing and exploring blog content.",
    date: "July - 2023",
    images: ["/blog-pc.png", "/blog-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "JavaScript",
      "NextAuth",
      "Firebase",
      "MongoDB",
      "Prisma",
    ],
    github: "https://github.com/YousifMHelal/postpeak",
  },
  {
    title: "Movie Vault",
    info: "Movie Vault is a movie listing application designed to help users search, browse, and explore movies efficiently. With features like infinite scroll, detailed movie information, and search functionality, Movie Vault offers an engaging experience for movie enthusiasts.",
    date: "January - 2024",
    images: ["/move-pc.png", "/move-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Server Actions",
    ],
    website: "https://movie-vault-cyan.vercel.app/",
    github: "https://github.com/YousifMHelal/movie-vault",
  },
  {
    title: "E-commerce Application",
    info: "Using my expertise in web development and e-commerce platforms, I built the website using modern technologies such as React, JavaScript, and Css. The website was optimized for speed and performance, ensuring that customers could browse and purchase products quickly and efficiently.",
    date: "December - 2022",
    images: ["/eco-pc.png", "/eco-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS"],
    website: "https://yousifmhelal.github.io/E-commerce/",
    github: "https://github.com/YousifMHelal/E-commerce",
  },
  {
    title: "Teba | Simple Description Website",
    info: "I worked on this project designing and developing using React, a powerful JavaScript library.",
    date: "May - 2023",
    images: ["/teba-pc.png", "/teba-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS"],
    website: "https://yousifmhelal.github.io/teba/",
    github: "https://github.com/YousifMHelal/teba",
  },
  {
    title: "Full-Stack Web developer | portfolio",
    info: "This portfolio website is designed to demonstrate my abilities as a Web Developer. It includes a variety of projects that I’ve worked on, highlighting my skills in both front-end and back-end development. The site is fully responsive and designed with modern web technologies.",
    date: "August - 2021",
    images: ["/portfolio-pc.png", "/portfolio-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS", "React router"],
    github: "https://github.com/YousifMHelal/Web-portfolio",
  },
];
