import { ItemType } from "@/components/ProjectCard";

export const Data: ItemType[] = [
  {
    title: "Trendy",
    info: "Trendy is a comprehensive e-commerce platform designed to provide a seamless shopping experience. The application offers robust authentication, product management, dynamic categorization, and secure checkout features.",
    date: "June - 2024",
    images: ["/ecom-pc.png", "/ecom-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "NextAuth",
      "Shadcn",
      "Stripe",
      "Zustand",
      "Firebase",
      "MongoDB",
      "Resend",
    ],
    website: "https://trendy-sigma.vercel.app/",
    github: "https://github.com/YousifMHelal/trendy",
  },
  {
    title: "Postpeak | Blogging Platform",
    info: "Postpeak is a dynamic blogging platform built with Next.js and Prisma. Users can sign up, log in, create posts, view other posts, comment on them, and filter posts by category. This application provides a user-friendly interface for managing and exploring blog content.",
    date: "July - 2023",
    images: ["/blog-pc.png", "/blog-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "JavaScript",
      "NextAuth",
      "Firebase",
      "MongoDB",
      "Prisma",
    ],
    github: "https://github.com/YousifMHelal/postpeak",
  },
  {
    title: "Movie Vault",
    info: "Movie Vault is a movie listing application designed to help users search, browse, and explore movies efficiently. With features like infinite scroll, detailed movie information, and search functionality, Movie Vault offers an engaging experience for movie enthusiasts.",
    date: "January - 2024",
    images: ["/move-pc.png", "/move-mb.png"],
    techs: [
      "Node.js",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Server Actions",
    ],
    website: "https://movie-vault-cyan.vercel.app/",
    github: "https://github.com/YousifMHelal/movie-vault",
  },
  {
    title: "E-commerce Application",
    info: "This React application is designed as the frontend interface for an e-commerce platform. It allows users to interact with product listings, perform searches, apply filters, and complete purchases. The design emphasizes a seamless and engaging user experience.",
    date: "December - 2022",
    images: ["/eco-pc.png", "/eco-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS"],
    website: "https://yousifmhelal.github.io/E-commerce/",
    github: "https://github.com/YousifMHelal/E-commerce",
  },
  {
    title: "Teba | Simple Description Website",
    info: "Teba is a React website serves as a digital presence for our company, which specializes in trading and distributing raw materials for detergents. The site provides information about the company, its products, and how to get in touch. It is designed to be user-friendly and responsive, ensuring a seamless experience across all devices.",
    date: "May - 2023",
    images: ["/teba-pc.png", "/teba-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS"],
    website: "https://yousifmhelal.github.io/teba/",
    github: "https://github.com/YousifMHelal/teba",
  },
  {
    title: "Full-Stack Web developer | portfolio",
    info: "This project is a fullstack web application designed to serve as a personal portfolio. It highlights my professional journey, including my skills, projects, and experience. The website is fully responsive, providing an optimal viewing experience across a wide range of devices.",
    date: "August - 2021",
    images: ["/portfolio-pc.png", "/portfolio-mb.png"],
    techs: ["Node.js", "React.js", "JavaScript", "TailwindCSS", "React router"],
    website: "https://web-portfolio-orcin-tau.vercel.app/",
    github: "https://github.com/YousifMHelal/Web-portfolio",
  },
];
